[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name =  "attendbot"
requires-python = "==3.12"
dynamic = ["version"]

[project.scripts]
attendbot = "main:run"
